Duplicate fd passed to fdopenr
fdopenr takes ownership of the file descriptor, whereas
the Python runtime still deems itself owner too, resulting
in conflicts e.g.

    close failed in file object destructor:
    IOError: [Errno 9] Bad file descriptor